### ISSUE TITLE
edits: Notifications settings

### ISSUE THREAD

**Issue by devinschumacher** [serpcompany/serp-extension#45]
- [ ] Add option for showing desktop notifications

<img width="450" alt="image" src="https://github.com/serpcompany/serp-extension/assets/45643901/35346f7e-920d-4183-aaeb-27fe355b79c7)">

# dark mode

- [ ] default all options windows to dark mode

example:

<img width="500" alt="image" src="https://github.com/serpcompany/serp-extension/assets/45643901/9c5ab1f5-84ed-4886-95de-9c3a350ae1b9">

<img width="500" alt="image" src="https://github.com/serpcompany/serp-extension/assets/45643901/642a8ff4-b78a-4f65-b843-6b817c751413">

**Comment by devinschumacher** [comment]
# fix URL destination

- [ ] see: https://www.loom.com/share/7223f18b04554732a444b9c5be2d6974

**Comment by devinschumacher** [comment]
# Faster access to notifications

Mission: How do we get to our GitHub notifications through our extension with less clicks??


# Tasks:

- [ ] change the word `Notification` in the tab to `Notifications`
- [ ] put the Notifications tab at the top and be the default tab selected upon extension click

## Ideas:

- Are we able to set a custom hotkey like `cmd+click on extension icon` to trigger the behavior of going to github?

**Comment by devinschumacher** [comment]
@mittalyashu

**Comment by mittalyashu** [comment]
@devinschumacher This Github issue contains multiple tasks scattered in multiple comments.

I will address each of them in separate PR 🙂

**Comment by devinschumacher** [comment]
@mittalyashu sounds good! i will close this issue assuming you have separated them out!
